export { default as App } from './App';
export * from './Tablas/AccionesTabla';
export * from './Tablas/ContentAccionesTabla';
export * from './Tablas/Paginacion';
export * from './Tablas/TablaCategorias';
export { default as Btncerrar } from './components/atomos/Btncerrar';
export * from './components/atomos/ColorContext';
export * from './components/atomos/ContentFiltro';
export * from './components/atomos/ContentHeader';
export * from './components/atomos/CustomFilters';
export * from './components/atomos/Iconos';
export { default as InputBuscadorLista } from './components/atomos/InputBuscadorLista';
export { default as BTNBoton } from './components/moleculas/BTNBoton';
export { default as BTNSave } from './components/moleculas/BTNSave';
export { default as BTNdesplegable } from './components/moleculas/BTNdesplegable';
export { default as BtnCirculas } from './components/moleculas/BtnCirculas';
export { default as ItemMenuDesplegable } from './components/moleculas/ItemMenuDesplegable';
export { default as ListaMenuDespegable } from './components/moleculas/ListaMenuDespegable';
export { default as Listagenerica } from './components/moleculas/Listagenerica';
export * from './components/moleculas/Spinner';
export { default as DataUser } from './components/organismos/DataUser';
export { default as DataUser2 } from './components/organismos/DataUser2';
export { default as Header2 } from './components/organismos/Formularios/Header2';
export * from './components/organismos/Formularios/InputText';
export * from './components/organismos/Formularios/RegistrarCategorias';
export { default as Header } from './components/organismos/Header';
export { default as Layout } from './components/organismos/Layout';
export { default as Layout2 } from './components/organismos/Layout2';
export { default as ListaPaises } from './components/organismos/ListaPaises';
export * from './components/organismos/LoaderSpinner';
export { default as MenuHambur } from './components/organismos/MenuHambur';
export { default as MenuHambur2 } from './components/organismos/MenuHambur2';
export { default as Selector } from './components/organismos/Selector';
export { default as SidebarCard } from './components/organismos/SidebarCard';
export { default as Slidebar } from './components/organismos/Slidebar';
export { default as Spinner } from './components/organismos/Spinner';
export { default as Spinner2 } from './components/organismos/Spinner2';
export { default as Success } from './components/organismos/Success';
export { default as CategoriasTempleted } from './components/templetes/CategoriasTempleted';
export { default as ConfigTempletes } from './components/templetes/ConfigTempletes';
export { default as Formulario } from './components/templetes/Formulario';
export { default as Formulario1 } from './components/templetes/Formulario1';
export { default as HomeTempledes } from './components/templetes/HomeTempledes';
export { default as LoginTempledes } from './components/templetes/LoginTempledes';
export { default as PlantillaBase } from './components/templetes/PlantillaBase';
export { default as SingupTempledes } from './components/templetes/SingupTempledes';
export { default as ContextLogin1 } from './context/ContextLogin1';
export { default as UseContext1 } from './context/UseContext1';
export * from './main';
export { default as Categorias } from './pages/Categorias';
export { default as Configuracion, } from './pages/Configuracion,';
export { default as ErrorsingUp } from './pages/ErrorsingUp';
export { default as Home } from './pages/Home';
export { default as Login } from './pages/Login';
export { default as Mapa } from './pages/Mapa';
export { default as Perfil } from './pages/Perfil';
export { default as SingUp } from './pages/SingUp';
export * from './routers/routes';
export * from './store/CategoriasStore';
export * from './store/OperacionesStore';
export * from './store/UsuarioStore';
export * from './styles/Breakpoints';
export * from './styles/themes';
export * from './styles/variables';
export * from './superbase/CrudCategorias';
export * from './superbase/Supabaseconect';
export * from './superbase/crudUsuario';
export * from './superbase/globalSupabase';
export * from './utils/Conversiones';
export * from './utils/dataStatic';
